version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./volumes/mongo:/data/db
    logging:
      driver: none
  vue:
    image: node:8
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: npm run dev
