version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./volumes/mongo:/data/db
    logging:
      driver: none
  # data:
  #   image: python:3
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "1k"
  #       max-file: "2"
  #   depends_on:
  #     - mongo
  #   environment:
  #     PYTHONUSERBASE: /app/.packages
  #   # command: bash -c "pip install --user joblib; pip freeze > requirements.txt"
  #   command: python preprocess/run.py
  vue:
    image: node:8
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: npm run dev
  flask:
    image: python:3
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      PYTHONUSERBASE: /app/.packages
      FLASK_APP: server/__init__.py
      FLASK_DEBUG: 1
    # command: sleep infinity
    command: /app/.packages/bin/flask run --host=0.0.0.0
    # command: pip install --user -r requirements.txt
